package sk.upjs.ics.android.big6.provider;

import android.content.ContentProvider;
import android.content.ContentResolver;
import android.content.ContentValues;
import android.content.UriMatcher;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.net.Uri;
import java.util.List;

import sk.upjs.ics.android.util.Defaults;

import static sk.upjs.ics.android.util.Defaults.ALL_COLUMNS;
import static sk.upjs.ics.android.util.Defaults.AUTOGENERATED_ID;
import static sk.upjs.ics.android.util.Defaults.NO_CONTENT_OBSERVER;
import static sk.upjs.ics.android.util.Defaults.NO_GROUP_BY;
import static sk.upjs.ics.android.util.Defaults.NO_HAVING;
import static sk.upjs.ics.android.util.Defaults.NO_SELECTION;
import static sk.upjs.ics.android.util.Defaults.NO_SELECTION_ARGS;
import static sk.upjs.ics.android.util.Defaults.NO_SORT_ORDER;

public class Big6ContentProviderOld extends ContentProvider {
    public static final String AUTHORITY = "sk.upjs.ics.android.big6.Big6ContentProvider";

    public static final Uri TRAINING_HISTORY_CONTENT_URI = new Uri.Builder()
            .scheme(ContentResolver.SCHEME_CONTENT)
            .authority(AUTHORITY)
            .appendPath(Big6Provider.TrainingHistory.TABLE_NAME)
            .build();

    public static final Uri PHOTO_URI_CONTENT_URI = new Uri.Builder()
            .scheme(ContentResolver.SCHEME_CONTENT)
            .authority(AUTHORITY)
            .appendPath(Big6Provider.PhotoUri.TABLE_NAME)
            .build();

    private static final String MIME_TYPE_TRAINING_HISTORY = ContentResolver.CURSOR_ITEM_BASE_TYPE + "/vnd." + AUTHORITY + "." + Big6Provider.TrainingHistory.TABLE_NAME;

    private static final String MIME_TYPE_PHOTO_URI = ContentResolver.CURSOR_ITEM_BASE_TYPE + "/vnd." + AUTHORITY + "." + Big6Provider.PhotoUri.TABLE_NAME;

    public static final int URI_MATCH_TRAININGS = 0;

    public static final int URI_MATCH_PHOTO = 1;


    private UriMatcher uriMatcher = new UriMatcher(UriMatcher.NO_MATCH);

    private static final String[] COLUMN_NAMES = new String[]{
            Big6Provider.TrainingHistory._ID,
            Big6Provider.TrainingHistory.YEAR,
            Big6Provider.TrainingHistory.MONTH,
            Big6Provider.TrainingHistory.DAY,
            Big6Provider.TrainingHistory.TRAINING,
            Big6Provider.TrainingHistory.TYPE
    };
    private DatabaseOpenHelper databaseOpenHelper;

    @Override
    public boolean onCreate() {
        uriMatcher.addURI(AUTHORITY, Big6Provider.TrainingHistory.TABLE_NAME, URI_MATCH_TRAININGS);
        uriMatcher.addURI(AUTHORITY, Big6Provider.PhotoUri.TABLE_NAME, URI_MATCH_PHOTO);

        databaseOpenHelper = new DatabaseOpenHelper(this.getContext());

        return true;
    }

    @Override
    public Cursor query(Uri uri, String[] projection, String selection,
                        String[] selectionArgs, String sortOrder) {
        switch(uriMatcher.match(uri)) {
            case URI_MATCH_TRAININGS:
                Cursor cursor = getTrainingsCursor();
                cursor.setNotificationUri(getContext().getContentResolver(), uri);
                return cursor;
            case URI_MATCH_PHOTO:
                Cursor cursor1 = getPhotoCursor();
                cursor1.setNotificationUri(getContext().getContentResolver(), uri);
            default:
                return null;
        }
    }

    private Cursor getPhotoCursor() {
        SQLiteDatabase db = databaseOpenHelper.getReadableDatabase();
        Cursor cursor = db.query(Big6Provider.PhotoUri.TABLE_NAME,
                ALL_COLUMNS,
                NO_SELECTION,
                NO_SELECTION_ARGS,
                NO_GROUP_BY,
                NO_HAVING,
                NO_SORT_ORDER);
        return cursor;
    }

    private Cursor getTrainingsCursor(){
        SQLiteDatabase db = databaseOpenHelper.getReadableDatabase();
        Cursor cursor = db.query(Big6Provider.TrainingHistory.TABLE_NAME,
                ALL_COLUMNS,
                NO_SELECTION,
                NO_SELECTION_ARGS,
                NO_GROUP_BY,
                NO_HAVING,
                NO_SORT_ORDER);
        return cursor;
    }

    @Override
    public int delete(Uri uri, String selection, String[] selectionArgs) {
        throw new UnsupportedOperationException("Not yet implemented");
    }

    @Override
    public String getType(Uri uri) {
        switch(uriMatcher.match(uri)){
            case URI_MATCH_TRAININGS:
                return MIME_TYPE_TRAINING_HISTORY;
            case URI_MATCH_PHOTO:
                return MIME_TYPE_PHOTO_URI;
            default:
                return null;
        }
    }

    @Override
    public Uri insert(Uri uri, ContentValues values) {
        switch(uriMatcher.match(uri)){
            case URI_MATCH_TRAININGS:
                List<String> segments = uri.getPathSegments();
                int year = Integer.parseInt(segments.get(1));
                int month = Integer.parseInt(segments.get(2));
                int day = Integer.parseInt(segments.get(3));
                String trainingvalues = segments.get(4);
                int type = Integer.parseInt(segments.get(5));

                ContentValues newContentValues = new ContentValues();
                newContentValues.put(Big6Provider.TrainingHistory._ID, AUTOGENERATED_ID);
                newContentValues.put(Big6Provider.TrainingHistory.YEAR, year);
                newContentValues.put(Big6Provider.TrainingHistory.MONTH, month);
                newContentValues.put(Big6Provider.TrainingHistory.DAY, day);
                newContentValues.put(Big6Provider.TrainingHistory.TRAINING, trainingvalues);
                newContentValues.put(Big6Provider.TrainingHistory.TYPE, type);

                databaseOpenHelper.getWritableDatabase()
                        .insert(Big6Provider.TrainingHistory.TABLE_NAME, Defaults.NO_NULL_COLUMN_HACK, newContentValues);
                Uri monthUri = TRAINING_HISTORY_CONTENT_URI
                        .buildUpon()
                        .appendPath(String.valueOf(year))
                        .appendPath(String.valueOf(month))
                        .build();
                getContext()
                        .getContentResolver()
                        .notifyChange(monthUri, NO_CONTENT_OBSERVER);

                return uri;

            case URI_MATCH_PHOTO:
                List<String> segments1 = uri.getPathSegments();
                String photoUri = segments1.get(1);
                int year1 = Integer.parseInt(segments1.get(2));
                int month1 = Integer.parseInt(segments1.get(3));
                int day1 = Integer.parseInt(segments1.get(4));
                String description = segments1.get(5);

                ContentValues photoContentValues = new ContentValues();
                photoContentValues.put(Big6Provider.PhotoUri._ID, AUTOGENERATED_ID);
                photoContentValues.put(Big6Provider.PhotoUri.URI, photoUri);
                photoContentValues.put(Big6Provider.PhotoUri.YEAR, year1);
                photoContentValues.put(Big6Provider.PhotoUri.MONTH, month1);
                photoContentValues.put(Big6Provider.PhotoUri.DAY, day1);
                photoContentValues.put(Big6Provider.PhotoUri.DESCRIPTION, description);

                databaseOpenHelper.getWritableDatabase()
                        .insert(Big6Provider.TrainingHistory.TABLE_NAME, Defaults.NO_NULL_COLUMN_HACK, photoContentValues);
                /*Uri monthUri = TRAINING_HISTORY_CONTENT_URI
                        .buildUpon()
                        .appendPath(String.valueOf(year))
                        .appendPath(String.valueOf(month))
                        .build();
                getContext()
                        .getContentResolver()
                        .notifyChange(monthUri, NO_CONTENT_OBSERVER);
                */
                return uri;
        }
        return null;
    }

    @Override
    public int update(Uri uri, ContentValues values, String selection,
                      String[] selectionArgs) {
        throw new UnsupportedOperationException("Not yet implemented");
    }
}

